import { useState } from "react";
import { UserProfile } from "../types";
// import { jsPDF } from "jspdf";
import { Download, Award, BookOpen, PenTool, CheckCircle, Globe, User } from "lucide-react";
import { SEO } from "./SEO";

interface ProfileProps {
  user: UserProfile | null;
}

const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "hi", name: "Hindi" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
];

export function Profile({ user }: ProfileProps) {
  const [isUpdating, setIsUpdating] = useState(false);

  if (!user) {
    return (
      <div className="text-center py-20 bg-white rounded-3xl border border-black/5 shadow-sm">
        <SEO title="Guest Profile" description="Login to Readative to access your full profile." />
        <div className="w-24 h-24 bg-gray-100 rounded-full mx-auto mb-6 flex items-center justify-center">
          <User className="w-10 h-10 text-gray-400" />
        </div>
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Guest User</h2>
        <p className="text-gray-500 mb-8">Login to track your reading progress, take exams, and customize your profile.</p>
        {/* The login button is in the header, so we can just guide them there or leave it as information */}
      </div>
    );
  }

  const handleLanguageChange = async (langCode: string) => {
    setIsUpdating(true);
    const updatedUser = { ...user, preferredLanguage: langCode };
    
    // Optimistic update (in real app, wait for API)
    // setUser(updatedUser); // Parent handles state, so we just call API
    
    await fetch(`/api/profile/${user.id}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(updatedUser)
    });
    
    // Force reload to reflect changes (in a real app, we'd use a context or callback)
    window.location.reload(); 
    setIsUpdating(false);
  };

  const downloadReport = () => {
    // const doc = new jsPDF();
    
    // // Header
    // doc.setFillColor(16, 185, 129); // Emerald 600
    // doc.rect(0, 0, 210, 40, 'F');
    
    // doc.setTextColor(255, 255, 255);
    // doc.setFontSize(24);
    // doc.text("READATIVE OFFICIAL REPORT", 105, 25, { align: 'center' });
    
    // // User Info
    // doc.setTextColor(26, 26, 26);
    // doc.setFontSize(16);
    // doc.text(`Student: ${user.name}`, 20, 60);
    // doc.setFontSize(12);
    // doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 70);
    
    // // Stats
    // doc.setDrawColor(230, 230, 230);
    // doc.line(20, 80, 190, 80);
    
    // doc.setFontSize(14);
    // doc.text("Performance Summary", 20, 95);
    
    // doc.setFontSize(12);
    // doc.text(`Reading Score: ${user.readingScore}`, 30, 110);
    // doc.text(`Exam Score: ${user.examScore}`, 30, 120);
    // doc.text(`Total Posts Read: ${user.readPosts.length}`, 30, 130);
    
    // // Signature
    // doc.setFont("courier", "italic");
    // doc.setFontSize(14);
    // doc.text("Readative Official", 150, 180);
    // doc.line(140, 185, 190, 185);
    // doc.setFontSize(10);
    // doc.text("Authorized Digital Signature", 145, 192);
    
    // // Footer
    // doc.setFont("helvetica", "normal");
    // doc.setFontSize(8);
    // doc.setTextColor(150, 150, 150);
    // doc.text("This is an official document generated by Readative AI.", 105, 280, { align: 'center' });
    
    // doc.save(`${user.name}-readative-report.pdf`);
    alert("PDF download temporarily disabled for debugging.");
  };

  return (
    <div className="space-y-6">
      <SEO 
        title={`${user.name}'s Profile`} 
        description={`Check out ${user.name}'s reading and writing progress on Readative.`}
        type="profile"
      />
      {/* Profile Header */}
      <div className="bg-white rounded-3xl p-8 border border-black/5 shadow-sm text-center">
        <div className="relative inline-block mb-6">
          <div className="w-32 h-32 rounded-full border-4 border-emerald-50 overflow-hidden mx-auto">
            <img src={user.photo} alt={user.name} className="w-full h-full object-cover" />
          </div>
          <div className="absolute bottom-0 right-0 bg-emerald-600 text-white p-2 rounded-full border-4 border-white">
            <Award className="w-5 h-5" />
          </div>
        </div>
        <h2 className="text-3xl font-bold text-gray-900 mb-1">{user.name}</h2>
        <p className="text-emerald-600 font-medium mb-6">Avid Reader & Writer</p>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-emerald-50 p-4 rounded-2xl">
            <p className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-1">Reading Score</p>
            <p className="text-2xl font-black text-emerald-900">{user.readingScore}</p>
          </div>
          <div className="bg-emerald-50 p-4 rounded-2xl">
            <p className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-1">Exam Score</p>
            <p className="text-2xl font-black text-emerald-900">{user.examScore}</p>
          </div>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-100">
          <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center justify-center gap-2">
            <Globe className="w-4 h-4" />
            Translation Settings
          </h3>
          <div className="flex flex-wrap justify-center gap-2">
            {LANGUAGES.map((lang) => (
              <button
                key={lang.code}
                onClick={() => handleLanguageChange(lang.name)}
                disabled={isUpdating}
                className={`px-4 py-2 rounded-xl text-sm font-bold transition-all ${
                  (user.preferredLanguage || "English") === lang.name
                    ? "bg-emerald-600 text-white shadow-md"
                    : "bg-gray-50 text-gray-600 hover:bg-gray-100"
                }`}
              >
                {lang.name}
              </button>
            ))}
          </div>
          <p className="text-xs text-gray-400 mt-2">Select your preferred language for post translations.</p>
        </div>
      </div>

      {/* Stats & Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white rounded-3xl p-6 border border-black/5 shadow-sm">
          <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-emerald-600" />
            Reading Activity
          </h3>
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-sm text-gray-500">Posts Read</span>
              <span className="font-bold">{user.readPosts.length}</span>
            </div>
            <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
              <div className="bg-emerald-600 h-full" style={{ width: `${Math.min(user.readPosts.length * 5, 100)}%` }} />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-3xl p-6 border border-black/5 shadow-sm flex flex-col justify-between">
          <div>
            <h3 className="font-bold text-gray-900 mb-2 flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-emerald-600" />
              Official Report
            </h3>
            <p className="text-sm text-gray-500 mb-6">Download your certified reading and exam performance report.</p>
          </div>
          <button 
            onClick={downloadReport}
            className="w-full bg-emerald-900 text-white py-4 rounded-2xl font-bold hover:bg-black transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download PDF Report
          </button>
        </div>
      </div>

      {/* Support Info */}
      <div className="text-center py-8">
        <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">Need Help?</p>
        <a 
          href="mailto:reader@readative.com" 
          className="text-sm font-medium text-emerald-600 hover:underline"
        >
          reader@readative.com
        </a>
      </div>
    </div>
  );
}
